FROM python:3.12-slim

WORKDIR /app

COPY serve/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ml/ ./ml/
COPY serve/ ./serve/

ENV BUCKET_NAME=mlops-demo-registry-379478996241
CMD ["uvicorn", "serve.app:app", "--host", "0.0.0.0", "--port", "80"]
