name: CD – deploy inference

on:
  workflow_run:
    workflows: ["CI – train model"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      # 1️⃣  AWS credentials first
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ secrets.AWS_REGION }}

      # 2️⃣  Log in to ECR (now the creds exist)
      - name: Authenticate Docker to ECR
        uses: aws-actions/amazon-ecr-login@v2

      # 3️⃣  Build **and push** the image
      - name: Build & push inference image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.infer
          push: true
          tags: ${{ secrets.ECR_REPO }}:latest

      # 4️⃣  Deploy updated task definition / service
      - name: Terraform apply
        run: terraform -chdir=infra apply -auto-approve
